# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose-2.4.yml up -d
version: '3.8'
# docker-compose -f docker-compose-app.yml up -d
# 你需要修改system为你自身系统的仓库名
services:
  xfg-dev-tech-docker-deploy:
    #image: system/xfg-dev-tech-docker-deploy:1.0-SNAPSHOT
    #image: fuzhengwei/xfg-dev-tech-docker-deploy:1.0-SNAPSHOT
#    image: registry.cn-hangzhou.aliyuncs.com/fuzhengwei/xfg-dev-tech-docker-deploy-app:1.2-SNAPSHOT
    image: fuzhengwei/xfg-dev-tech-docker-deploy-app:1.5-SNAPSHOT
    container_name: xfg-dev-tech-docker-deploy
    restart: on-failure
    ports:
      - "8091:8091"
    environment:
      - TZ=PRC
      - SERVER_PORT=8091
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://111.229.28.45:13306/deploy_data?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - REDIS_SDK_CONFIG_HOST=redis
      - REDIS_SDK_CONFIG_PORT=6379
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
